# CMake generated Testfile for 
# Source directory: /home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test
# Build directory: /home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/InteractionModel/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(InteractionModelCapabilityAgentTest.test_createNoDirectiveSequencer "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/InteractionModel/test/InteractionModelCapabilityAgentTest" "--gtest_filter=InteractionModelCapabilityAgentTest.test_createNoDirectiveSequencer")
set_tests_properties(InteractionModelCapabilityAgentTest.test_createNoDirectiveSequencer PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;0;")
add_test(InteractionModelCapabilityAgentTest.test_createNoExceptionHanlder "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/InteractionModel/test/InteractionModelCapabilityAgentTest" "--gtest_filter=InteractionModelCapabilityAgentTest.test_createNoExceptionHanlder")
set_tests_properties(InteractionModelCapabilityAgentTest.test_createNoExceptionHanlder PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;0;")
add_test(InteractionModelCapabilityAgentTest.test_processNewDialogRequestID "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/InteractionModel/test/InteractionModelCapabilityAgentTest" "--gtest_filter=InteractionModelCapabilityAgentTest.test_processNewDialogRequestID")
set_tests_properties(InteractionModelCapabilityAgentTest.test_processNewDialogRequestID PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;0;")
add_test(InteractionModelCapabilityAgentTest.test_processNullDirective "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/InteractionModel/test/InteractionModelCapabilityAgentTest" "--gtest_filter=InteractionModelCapabilityAgentTest.test_processNullDirective")
set_tests_properties(InteractionModelCapabilityAgentTest.test_processNullDirective PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;0;")
add_test(InteractionModelCapabilityAgentTest.test_processInvalidDirective "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/InteractionModel/test/InteractionModelCapabilityAgentTest" "--gtest_filter=InteractionModelCapabilityAgentTest.test_processInvalidDirective")
set_tests_properties(InteractionModelCapabilityAgentTest.test_processInvalidDirective PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;0;")
add_test(InteractionModelCapabilityAgentTest.test_addObserverRPS "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/InteractionModel/test/InteractionModelCapabilityAgentTest" "--gtest_filter=InteractionModelCapabilityAgentTest.test_addObserverRPS")
set_tests_properties(InteractionModelCapabilityAgentTest.test_addObserverRPS PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;0;")
add_test(InteractionModelCapabilityAgentTest.test_addObserverRPC "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/InteractionModel/test/InteractionModelCapabilityAgentTest" "--gtest_filter=InteractionModelCapabilityAgentTest.test_addObserverRPC")
set_tests_properties(InteractionModelCapabilityAgentTest.test_addObserverRPC PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;0;")
add_test(InteractionModelCapabilityAgentTest.test_addObserverNullptr_NoErrors "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/InteractionModel/test/InteractionModelCapabilityAgentTest" "--gtest_filter=InteractionModelCapabilityAgentTest.test_addObserverNullptr_NoErrors")
set_tests_properties(InteractionModelCapabilityAgentTest.test_addObserverNullptr_NoErrors PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;0;")
add_test(InteractionModelCapabilityAgentTest.test_removeObserver "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/InteractionModel/test/InteractionModelCapabilityAgentTest" "--gtest_filter=InteractionModelCapabilityAgentTest.test_removeObserver")
set_tests_properties(InteractionModelCapabilityAgentTest.test_removeObserver PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;0;")
add_test(InteractionModelCapabilityAgentTest.test_removeObserverNullptr_NoErrors "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/InteractionModel/test/InteractionModelCapabilityAgentTest" "--gtest_filter=InteractionModelCapabilityAgentTest.test_removeObserverNullptr_NoErrors")
set_tests_properties(InteractionModelCapabilityAgentTest.test_removeObserverNullptr_NoErrors PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/InteractionModel/test/CMakeLists.txt;0;")
