# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test
# Build directory: /home/pi/sdk-folder/sdk-build/KWD/Sensory/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(SensoryKeywordTest.test_invalidStream "/home/pi/sdk-folder/sdk-build/KWD/Sensory/test/SensoryKeywordDetectorTest" "--gtest_filter=SensoryKeywordTest.test_invalidStream" "/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/inputs")
set_tests_properties(SensoryKeywordTest.test_invalidStream PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;5;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;0;")
add_test(SensoryKeywordTest.test_incompatibleEndianness "/home/pi/sdk-folder/sdk-build/KWD/Sensory/test/SensoryKeywordDetectorTest" "--gtest_filter=SensoryKeywordTest.test_incompatibleEndianness" "/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/inputs")
set_tests_properties(SensoryKeywordTest.test_incompatibleEndianness PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;5;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;0;")
add_test(SensoryKeywordTest.test_getExpectedNumberOfDetectionsInFourAlexasAudioFileForOneObserver "/home/pi/sdk-folder/sdk-build/KWD/Sensory/test/SensoryKeywordDetectorTest" "--gtest_filter=SensoryKeywordTest.test_getExpectedNumberOfDetectionsInFourAlexasAudioFileForOneObserver" "/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/inputs")
set_tests_properties(SensoryKeywordTest.test_getExpectedNumberOfDetectionsInFourAlexasAudioFileForOneObserver PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;5;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;0;")
add_test(SensoryKeywordTest.test_getExpectedNumberOfDetectionsInFourAlexasAudioFileForTwoObservers "/home/pi/sdk-folder/sdk-build/KWD/Sensory/test/SensoryKeywordDetectorTest" "--gtest_filter=SensoryKeywordTest.test_getExpectedNumberOfDetectionsInFourAlexasAudioFileForTwoObservers" "/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/inputs")
set_tests_properties(SensoryKeywordTest.test_getExpectedNumberOfDetectionsInFourAlexasAudioFileForTwoObservers PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;5;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;0;")
add_test(SensoryKeywordTest.test_getExpectedNumberOfDetectionsInAlexaStopAlexaJokeAudioFileForOneObserver "/home/pi/sdk-folder/sdk-build/KWD/Sensory/test/SensoryKeywordDetectorTest" "--gtest_filter=SensoryKeywordTest.test_getExpectedNumberOfDetectionsInAlexaStopAlexaJokeAudioFileForOneObserver" "/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/inputs")
set_tests_properties(SensoryKeywordTest.test_getExpectedNumberOfDetectionsInAlexaStopAlexaJokeAudioFileForOneObserver PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;5;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;0;")
add_test(SensoryKeywordTest.test_getActiveState "/home/pi/sdk-folder/sdk-build/KWD/Sensory/test/SensoryKeywordDetectorTest" "--gtest_filter=SensoryKeywordTest.test_getActiveState" "/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/inputs")
set_tests_properties(SensoryKeywordTest.test_getActiveState PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;5;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;0;")
add_test(SensoryKeywordTest.test_getStreamClosedState "/home/pi/sdk-folder/sdk-build/KWD/Sensory/test/SensoryKeywordDetectorTest" "--gtest_filter=SensoryKeywordTest.test_getStreamClosedState" "/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/inputs")
set_tests_properties(SensoryKeywordTest.test_getStreamClosedState PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;5;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;0;")
add_test(SensoryKeywordTest.test_getExpectedNumberOfDetectionsInAlexaStopAlexaJokeAudioFileWithRandomDataAtBeginning "/home/pi/sdk-folder/sdk-build/KWD/Sensory/test/SensoryKeywordDetectorTest" "--gtest_filter=SensoryKeywordTest.test_getExpectedNumberOfDetectionsInAlexaStopAlexaJokeAudioFileWithRandomDataAtBeginning" "/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/inputs")
set_tests_properties(SensoryKeywordTest.test_getExpectedNumberOfDetectionsInAlexaStopAlexaJokeAudioFileWithRandomDataAtBeginning PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;5;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/Sensory/test/CMakeLists.txt;0;")
