# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test
# Build directory: /home/pi/sdk-folder/sdk-build/shared/acsdkStartupManager/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(StartupManagerTest.test_simplestFailureCase "/home/pi/sdk-folder/sdk-build/shared/acsdkStartupManager/test/StartupManagerTest" "--gtest_filter=StartupManagerTest.test_simplestFailureCase")
set_tests_properties(StartupManagerTest.test_simplestFailureCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;0;")
add_test(StartupManagerTest.test_simplestSuccessCase "/home/pi/sdk-folder/sdk-build/shared/acsdkStartupManager/test/StartupManagerTest" "--gtest_filter=StartupManagerTest.test_simplestSuccessCase")
set_tests_properties(StartupManagerTest.test_simplestSuccessCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;0;")
add_test(StartupManagerTest.test_simpleSuccessCase "/home/pi/sdk-folder/sdk-build/shared/acsdkStartupManager/test/StartupManagerTest" "--gtest_filter=StartupManagerTest.test_simpleSuccessCase")
set_tests_properties(StartupManagerTest.test_simpleSuccessCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;0;")
add_test(StartupManagerTest.test_complexSuccessCase "/home/pi/sdk-folder/sdk-build/shared/acsdkStartupManager/test/StartupManagerTest" "--gtest_filter=StartupManagerTest.test_complexSuccessCase")
set_tests_properties(StartupManagerTest.test_complexSuccessCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;0;")
add_test(StartupManagerTest.test_simpleFailCase "/home/pi/sdk-folder/sdk-build/shared/acsdkStartupManager/test/StartupManagerTest" "--gtest_filter=StartupManagerTest.test_simpleFailCase")
set_tests_properties(StartupManagerTest.test_simpleFailCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;0;")
add_test(StartupManagerTest.test_complexFailureCase "/home/pi/sdk-folder/sdk-build/shared/acsdkStartupManager/test/StartupManagerTest" "--gtest_filter=StartupManagerTest.test_complexFailureCase")
set_tests_properties(StartupManagerTest.test_complexFailureCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkStartupManager/test/CMakeLists.txt;0;")
