# CMake generated Testfile for 
# Source directory: /home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test
# Build directory: /home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(SoftwareComponentReporterCapabilityAgentTest.test_addComponentConfiguration "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test/SoftwareComponentReporterCapabilityAgentTest" "--gtest_filter=SoftwareComponentReporterCapabilityAgentTest.test_addComponentConfiguration")
set_tests_properties(SoftwareComponentReporterCapabilityAgentTest.test_addComponentConfiguration PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test/CMakeLists.txt;6;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test/CMakeLists.txt;0;")
add_test(SoftwareComponentReporterCapabilityAgentTest.test_addMultipleComponentConfiguration "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test/SoftwareComponentReporterCapabilityAgentTest" "--gtest_filter=SoftwareComponentReporterCapabilityAgentTest.test_addMultipleComponentConfiguration")
set_tests_properties(SoftwareComponentReporterCapabilityAgentTest.test_addMultipleComponentConfiguration PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test/CMakeLists.txt;6;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test/CMakeLists.txt;0;")
add_test(SoftwareComponentReporterCapabilityAgentTest.test_addDupeComponentConfiguration "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test/SoftwareComponentReporterCapabilityAgentTest" "--gtest_filter=SoftwareComponentReporterCapabilityAgentTest.test_addDupeComponentConfiguration")
set_tests_properties(SoftwareComponentReporterCapabilityAgentTest.test_addDupeComponentConfiguration PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test/CMakeLists.txt;6;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test/CMakeLists.txt;0;")
add_test(SoftwareComponentReporterCapabilityAgentTest.test_configurationJsonBuilds "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test/SoftwareComponentReporterCapabilityAgentTest" "--gtest_filter=SoftwareComponentReporterCapabilityAgentTest.test_configurationJsonBuilds")
set_tests_properties(SoftwareComponentReporterCapabilityAgentTest.test_configurationJsonBuilds PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test/CMakeLists.txt;6;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test/CMakeLists.txt;0;")
add_test(SoftwareComponentReporterCapabilityAgentTest.test_configurationJsonEmpty "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CapabilityAgents/SoftwareComponentReporter/test/SoftwareComponentReporterCapabilityAgentTest" "--gtest_filter=SoftwareComponentReporterCapabilityAgentTest.test_configurationJsonEmpty")
set_tests_properties(SoftwareComponentReporterCapabilityAgentTest.test_configurationJsonEmpty PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test/CMakeLists.txt;6;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SoftwareComponentReporter/test/CMakeLists.txt;0;")
