# CMake generated Testfile for 
# Source directory: /home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test
# Build directory: /home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CertifiedSender/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CertifiedSenderTest.test_clearData "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CertifiedSender/test/CertifiedSenderTest" "--gtest_filter=CertifiedSenderTest.test_clearData" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test")
set_tests_properties(CertifiedSenderTest.test_clearData PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;9;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;0;")
add_test(CertifiedSenderTest.testTimer_SendMessageWithURI "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CertifiedSender/test/CertifiedSenderTest" "--gtest_filter=CertifiedSenderTest.testTimer_SendMessageWithURI" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test")
set_tests_properties(CertifiedSenderTest.testTimer_SendMessageWithURI PROPERTIES  LABELS "timertest" _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;9;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;0;")
add_test(MessageStorageTest.test_constructionAndDestruction "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CertifiedSender/test/MessageStorageTest" "--gtest_filter=MessageStorageTest.test_constructionAndDestruction" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test")
set_tests_properties(MessageStorageTest.test_constructionAndDestruction PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;9;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;0;")
add_test(MessageStorageTest.test_databaseCreation "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CertifiedSender/test/MessageStorageTest" "--gtest_filter=MessageStorageTest.test_databaseCreation" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test")
set_tests_properties(MessageStorageTest.test_databaseCreation PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;9;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;0;")
add_test(MessageStorageTest.test_openAndCloseDatabase "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CertifiedSender/test/MessageStorageTest" "--gtest_filter=MessageStorageTest.test_openAndCloseDatabase" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test")
set_tests_properties(MessageStorageTest.test_openAndCloseDatabase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;9;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;0;")
add_test(MessageStorageTest.test_databaseStoreAndLoad "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CertifiedSender/test/MessageStorageTest" "--gtest_filter=MessageStorageTest.test_databaseStoreAndLoad" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test")
set_tests_properties(MessageStorageTest.test_databaseStoreAndLoad PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;9;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;0;")
add_test(MessageStorageTest.test_databaseErase "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CertifiedSender/test/MessageStorageTest" "--gtest_filter=MessageStorageTest.test_databaseErase" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test")
set_tests_properties(MessageStorageTest.test_databaseErase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;9;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;0;")
add_test(MessageStorageTest.test_databaseClear "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CertifiedSender/test/MessageStorageTest" "--gtest_filter=MessageStorageTest.test_databaseClear" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test")
set_tests_properties(MessageStorageTest.test_databaseClear PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;9;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;0;")
add_test(MessageStorageTest.testDatabaseStoreAndLoadWithURI "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/CertifiedSender/test/MessageStorageTest" "--gtest_filter=MessageStorageTest.testDatabaseStoreAndLoadWithURI" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test")
set_tests_properties(MessageStorageTest.testDatabaseStoreAndLoadWithURI PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;9;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/CertifiedSender/test/CMakeLists.txt;0;")
subdirs("Common")
