# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkShutdownManager/test
# Build directory: /home/pi/sdk-folder/sdk-build/shared/acsdkShutdownManager/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ShutdownManagerTest.test_simplestFailureCase "/home/pi/sdk-folder/sdk-build/shared/acsdkShutdownManager/test/ShutdownManagerTest" "--gtest_filter=ShutdownManagerTest.test_simplestFailureCase")
set_tests_properties(ShutdownManagerTest.test_simplestFailureCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkShutdownManager/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkShutdownManager/test/CMakeLists.txt;0;")
add_test(ShutdownManagerTest.test_simplestSuccessCase "/home/pi/sdk-folder/sdk-build/shared/acsdkShutdownManager/test/ShutdownManagerTest" "--gtest_filter=ShutdownManagerTest.test_simplestSuccessCase")
set_tests_properties(ShutdownManagerTest.test_simplestSuccessCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkShutdownManager/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkShutdownManager/test/CMakeLists.txt;0;")
add_test(ShutdownManagerTest.test_simpleSuccessCase "/home/pi/sdk-folder/sdk-build/shared/acsdkShutdownManager/test/ShutdownManagerTest" "--gtest_filter=ShutdownManagerTest.test_simpleSuccessCase")
set_tests_properties(ShutdownManagerTest.test_simpleSuccessCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkShutdownManager/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkShutdownManager/test/CMakeLists.txt;0;")
add_test(ShutdownManagerTest.test_simpleFailureCase "/home/pi/sdk-folder/sdk-build/shared/acsdkShutdownManager/test/ShutdownManagerTest" "--gtest_filter=ShutdownManagerTest.test_simpleFailureCase")
set_tests_properties(ShutdownManagerTest.test_simpleFailureCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkShutdownManager/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkShutdownManager/test/CMakeLists.txt;0;")
