# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test
# Build directory: /home/pi/sdk-folder/sdk-build/KWD/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(AbstractKeyWordDetectorTest.test_addKeyWordObserver "/home/pi/sdk-folder/sdk-build/KWD/test/AbstractKeywordDetectorTest" "--gtest_filter=AbstractKeyWordDetectorTest.test_addKeyWordObserver")
set_tests_properties(AbstractKeyWordDetectorTest.test_addKeyWordObserver PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;1;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;0;")
add_test(AbstractKeyWordDetectorTest.test_addMultipleKeyWordObserver "/home/pi/sdk-folder/sdk-build/KWD/test/AbstractKeywordDetectorTest" "--gtest_filter=AbstractKeyWordDetectorTest.test_addMultipleKeyWordObserver")
set_tests_properties(AbstractKeyWordDetectorTest.test_addMultipleKeyWordObserver PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;1;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;0;")
add_test(AbstractKeyWordDetectorTest.test_removeKeyWordObserver "/home/pi/sdk-folder/sdk-build/KWD/test/AbstractKeywordDetectorTest" "--gtest_filter=AbstractKeyWordDetectorTest.test_removeKeyWordObserver")
set_tests_properties(AbstractKeyWordDetectorTest.test_removeKeyWordObserver PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;1;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;0;")
add_test(AbstractKeyWordDetectorTest.test_addStateObserver "/home/pi/sdk-folder/sdk-build/KWD/test/AbstractKeywordDetectorTest" "--gtest_filter=AbstractKeyWordDetectorTest.test_addStateObserver")
set_tests_properties(AbstractKeyWordDetectorTest.test_addStateObserver PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;1;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;0;")
add_test(AbstractKeyWordDetectorTest.test_addMultipleStateObservers "/home/pi/sdk-folder/sdk-build/KWD/test/AbstractKeywordDetectorTest" "--gtest_filter=AbstractKeyWordDetectorTest.test_addMultipleStateObservers")
set_tests_properties(AbstractKeyWordDetectorTest.test_addMultipleStateObservers PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;1;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;0;")
add_test(AbstractKeyWordDetectorTest.test_removeStateObserver "/home/pi/sdk-folder/sdk-build/KWD/test/AbstractKeywordDetectorTest" "--gtest_filter=AbstractKeyWordDetectorTest.test_removeStateObserver")
set_tests_properties(AbstractKeyWordDetectorTest.test_removeStateObserver PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;1;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;0;")
add_test(AbstractKeyWordDetectorTest.test_observersDontGetNotifiedOfSameStateTwice "/home/pi/sdk-folder/sdk-build/KWD/test/AbstractKeywordDetectorTest" "--gtest_filter=AbstractKeyWordDetectorTest.test_observersDontGetNotifiedOfSameStateTwice")
set_tests_properties(AbstractKeyWordDetectorTest.test_observersDontGetNotifiedOfSameStateTwice PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;1;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/test/CMakeLists.txt;0;")
