# CMake generated Testfile for 
# Source directory: /home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/capabilities/DoNotDisturb/acsdkDoNotDisturb/test
# Build directory: /home/pi/SmartMusicDisplay/sdk-folder/sdk-build/EXTENSION/DoNotDisturb/acsdkDoNotDisturb/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(DoNotDisturbCapabilityAgentTest.test_givenInvalidParameters_create_shouldFail "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/EXTENSION/DoNotDisturb/acsdkDoNotDisturb/test/DoNotDisturbCapabilityAgentTest" "--gtest_filter=DoNotDisturbCapabilityAgentTest.test_givenInvalidParameters_create_shouldFail")
set_tests_properties(DoNotDisturbCapabilityAgentTest.test_givenInvalidParameters_create_shouldFail PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/capabilities/DoNotDisturb/acsdkDoNotDisturb/test/CMakeLists.txt;12;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/capabilities/DoNotDisturb/acsdkDoNotDisturb/test/CMakeLists.txt;0;")
add_test(DoNotDisturbCapabilityAgentTest.test_givenValidSetDNDDirective_handleDirective_shouldSucceed "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/EXTENSION/DoNotDisturb/acsdkDoNotDisturb/test/DoNotDisturbCapabilityAgentTest" "--gtest_filter=DoNotDisturbCapabilityAgentTest.test_givenValidSetDNDDirective_handleDirective_shouldSucceed")
set_tests_properties(DoNotDisturbCapabilityAgentTest.test_givenValidSetDNDDirective_handleDirective_shouldSucceed PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/capabilities/DoNotDisturb/acsdkDoNotDisturb/test/CMakeLists.txt;12;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/capabilities/DoNotDisturb/acsdkDoNotDisturb/test/CMakeLists.txt;0;")
add_test(DoNotDisturbCapabilityAgentTest.test_beingOnline_applyLocalChange_shouldSendReport "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/EXTENSION/DoNotDisturb/acsdkDoNotDisturb/test/DoNotDisturbCapabilityAgentTest" "--gtest_filter=DoNotDisturbCapabilityAgentTest.test_beingOnline_applyLocalChange_shouldSendReport")
set_tests_properties(DoNotDisturbCapabilityAgentTest.test_beingOnline_applyLocalChange_shouldSendReport PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/capabilities/DoNotDisturb/acsdkDoNotDisturb/test/CMakeLists.txt;12;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/capabilities/DoNotDisturb/acsdkDoNotDisturb/test/CMakeLists.txt;0;")
add_test(DoNotDisturbCapabilityAgentTest.test_beingOffline_applyLocalChangeAndBecomeOnline_shouldSendChanged "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/EXTENSION/DoNotDisturb/acsdkDoNotDisturb/test/DoNotDisturbCapabilityAgentTest" "--gtest_filter=DoNotDisturbCapabilityAgentTest.test_beingOffline_applyLocalChangeAndBecomeOnline_shouldSendChanged")
set_tests_properties(DoNotDisturbCapabilityAgentTest.test_beingOffline_applyLocalChangeAndBecomeOnline_shouldSendChanged PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/capabilities/DoNotDisturb/acsdkDoNotDisturb/test/CMakeLists.txt;12;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/capabilities/DoNotDisturb/acsdkDoNotDisturb/test/CMakeLists.txt;0;")
add_test(DoNotDisturbCapabilityAgentTest.test_whileSendingChangedEvent_sendChangedFail_shouldSendReport "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/EXTENSION/DoNotDisturb/acsdkDoNotDisturb/test/DoNotDisturbCapabilityAgentTest" "--gtest_filter=DoNotDisturbCapabilityAgentTest.test_whileSendingChangedEvent_sendChangedFail_shouldSendReport")
set_tests_properties(DoNotDisturbCapabilityAgentTest.test_whileSendingChangedEvent_sendChangedFail_shouldSendReport PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/capabilities/DoNotDisturb/acsdkDoNotDisturb/test/CMakeLists.txt;12;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/capabilities/DoNotDisturb/acsdkDoNotDisturb/test/CMakeLists.txt;0;")
