# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test
# Build directory: /home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ManufactoryTest.test_manufactureUnique "/home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test/ManufactoryTest" "--gtest_filter=ManufactoryTest.test_manufactureUnique" "AVSCommon")
set_tests_properties(ManufactoryTest.test_manufactureUnique PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;0;")
add_test(ManufactoryTest.test_manufactureShared "/home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test/ManufactoryTest" "--gtest_filter=ManufactoryTest.test_manufactureShared" "AVSCommon")
set_tests_properties(ManufactoryTest.test_manufactureShared PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;0;")
add_test(ManufactoryTest.test_multipleInhertance "/home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test/ManufactoryTest" "--gtest_filter=ManufactoryTest.test_multipleInhertance" "AVSCommon")
set_tests_properties(ManufactoryTest.test_multipleInhertance PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;0;")
add_test(ManufactoryTest.test_annotatedManufacture "/home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test/ManufactoryTest" "--gtest_filter=ManufactoryTest.test_annotatedManufacture" "AVSCommon")
set_tests_properties(ManufactoryTest.test_annotatedManufacture PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;0;")
add_test(ManufactoryTest.test_retainedManufacture "/home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test/ManufactoryTest" "--gtest_filter=ManufactoryTest.test_retainedManufacture" "AVSCommon")
set_tests_properties(ManufactoryTest.test_retainedManufacture PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;0;")
add_test(ManufactoryTest.test_requiredManufacture "/home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test/ManufactoryTest" "--gtest_filter=ManufactoryTest.test_requiredManufacture" "AVSCommon")
set_tests_properties(ManufactoryTest.test_requiredManufacture PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;0;")
add_test(ManufactoryTest.test_primeManufacture "/home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test/ManufactoryTest" "--gtest_filter=ManufactoryTest.test_primeManufacture" "AVSCommon")
set_tests_properties(ManufactoryTest.test_primeManufacture PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;0;")
add_test(ManufactoryTest.test_functionManufacture "/home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test/ManufactoryTest" "--gtest_filter=ManufactoryTest.test_functionManufacture" "AVSCommon")
set_tests_properties(ManufactoryTest.test_functionManufacture PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;0;")
add_test(ManufactoryTest.test_anotatedFunctionManufacture "/home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test/ManufactoryTest" "--gtest_filter=ManufactoryTest.test_anotatedFunctionManufacture" "AVSCommon")
set_tests_properties(ManufactoryTest.test_anotatedFunctionManufacture PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;0;")
add_test(ManufactoryTest.test_checkCyclicDependencies "/home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test/ManufactoryTest" "--gtest_filter=ManufactoryTest.test_checkCyclicDependencies" "AVSCommon")
set_tests_properties(ManufactoryTest.test_checkCyclicDependencies PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;0;")
add_test(ManufactoryTest.test_subManufactory "/home/pi/sdk-folder/sdk-build/shared/acsdkManufactory/test/ManufactoryTest" "--gtest_filter=ManufactoryTest.test_subManufactory" "AVSCommon")
set_tests_properties(ManufactoryTest.test_subManufactory PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/shared/acsdkManufactory/test/CMakeLists.txt;0;")
