# CMake generated Testfile for 
# Source directory: /home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test
# Build directory: /home/pi/SmartMusicDisplay/sdk-folder/sdk-build/InterruptModel/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(InterruptModelTest.test_emptyConfiguration "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/InterruptModel/test/InterruptModelTest" "--gtest_filter=InterruptModelTest.test_emptyConfiguration" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test")
set_tests_properties(InterruptModelTest.test_emptyConfiguration PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;10;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;0;")
add_test(InterruptModelTest.test_NonExistentChannelConfigReturnsUndefined "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/InterruptModel/test/InterruptModelTest" "--gtest_filter=InterruptModelTest.test_NonExistentChannelConfigReturnsUndefined" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test")
set_tests_properties(InterruptModelTest.test_NonExistentChannelConfigReturnsUndefined PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;10;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;0;")
add_test(InterruptModelTest.test_MissingContentTypeKeyReturnsUndefined "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/InterruptModel/test/InterruptModelTest" "--gtest_filter=InterruptModelTest.test_MissingContentTypeKeyReturnsUndefined" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test")
set_tests_properties(InterruptModelTest.test_MissingContentTypeKeyReturnsUndefined PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;10;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;0;")
add_test(InterruptModelTest.test_MissingMixingBehaviorKeyReturnsUndefined "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/InterruptModel/test/InterruptModelTest" "--gtest_filter=InterruptModelTest.test_MissingMixingBehaviorKeyReturnsUndefined" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test")
set_tests_properties(InterruptModelTest.test_MissingMixingBehaviorKeyReturnsUndefined PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;10;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;0;")
add_test(InterruptModelTest.test_MissingConfigReturnsUndefined "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/InterruptModel/test/InterruptModelTest" "--gtest_filter=InterruptModelTest.test_MissingConfigReturnsUndefined" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test")
set_tests_properties(InterruptModelTest.test_MissingConfigReturnsUndefined PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;10;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;0;")
add_test(InterruptModelTest.test_MissingIncomingChannelKeyReturnsUndefined "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/InterruptModel/test/InterruptModelTest" "--gtest_filter=InterruptModelTest.test_MissingIncomingChannelKeyReturnsUndefined" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test")
set_tests_properties(InterruptModelTest.test_MissingIncomingChannelKeyReturnsUndefined PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;10;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;0;")
add_test(InterruptModelTest.test_UnspecifiedMixingBehaviorKeyReturnsUndefined "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/InterruptModel/test/InterruptModelTest" "--gtest_filter=InterruptModelTest.test_UnspecifiedMixingBehaviorKeyReturnsUndefined" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test")
set_tests_properties(InterruptModelTest.test_UnspecifiedMixingBehaviorKeyReturnsUndefined PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;10;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;0;")
add_test(InterruptModelTest.test_UnspecifiedIncomingMixingBehaviorReturnsUndefined "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/InterruptModel/test/InterruptModelTest" "--gtest_filter=InterruptModelTest.test_UnspecifiedIncomingMixingBehaviorReturnsUndefined" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test")
set_tests_properties(InterruptModelTest.test_UnspecifiedIncomingMixingBehaviorReturnsUndefined PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;10;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;0;")
add_test(InterruptModelTest.test_InvalidIncomingMixingBehaviorReturnsUndefined "/home/pi/SmartMusicDisplay/sdk-folder/sdk-build/InterruptModel/test/InterruptModelTest" "--gtest_filter=InterruptModelTest.test_InvalidIncomingMixingBehaviorReturnsUndefined" "/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test")
set_tests_properties(InterruptModelTest.test_InvalidIncomingMixingBehaviorReturnsUndefined PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;10;discover_unit_tests;/home/pi/SmartMusicDisplay/sdk-folder/sdk-source/avs-device-sdk/InterruptModel/test/CMakeLists.txt;0;")
