# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test
# Build directory: /home/pi/sdk-folder/sdk-build/core/acsdkPostConnectOperationProviderRegistrar/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(PostConnectOperationProviderRegistrarTest.test_simplestFailureCase "/home/pi/sdk-folder/sdk-build/core/acsdkPostConnectOperationProviderRegistrar/test/PostConnectOperationProviderRegistrarTest" "--gtest_filter=PostConnectOperationProviderRegistrarTest.test_simplestFailureCase")
set_tests_properties(PostConnectOperationProviderRegistrarTest.test_simplestFailureCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;0;")
add_test(PostConnectOperationProviderRegistrarTest.test_simplestSuccessCase "/home/pi/sdk-folder/sdk-build/core/acsdkPostConnectOperationProviderRegistrar/test/PostConnectOperationProviderRegistrarTest" "--gtest_filter=PostConnectOperationProviderRegistrarTest.test_simplestSuccessCase")
set_tests_properties(PostConnectOperationProviderRegistrarTest.test_simplestSuccessCase PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;0;")
add_test(PostConnectOperationProviderRegistrarTest.test_getProvidersBeforeStartup "/home/pi/sdk-folder/sdk-build/core/acsdkPostConnectOperationProviderRegistrar/test/PostConnectOperationProviderRegistrarTest" "--gtest_filter=PostConnectOperationProviderRegistrarTest.test_getProvidersBeforeStartup")
set_tests_properties(PostConnectOperationProviderRegistrarTest.test_getProvidersBeforeStartup PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;0;")
add_test(PostConnectOperationProviderRegistrarTest.test_getEmptyProvidersAfterStartup "/home/pi/sdk-folder/sdk-build/core/acsdkPostConnectOperationProviderRegistrar/test/PostConnectOperationProviderRegistrarTest" "--gtest_filter=PostConnectOperationProviderRegistrarTest.test_getEmptyProvidersAfterStartup")
set_tests_properties(PostConnectOperationProviderRegistrarTest.test_getEmptyProvidersAfterStartup PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;0;")
add_test(PostConnectOperationProviderRegistrarTest.test_getProvidersAfterStartup "/home/pi/sdk-folder/sdk-build/core/acsdkPostConnectOperationProviderRegistrar/test/PostConnectOperationProviderRegistrarTest" "--gtest_filter=PostConnectOperationProviderRegistrarTest.test_getProvidersAfterStartup")
set_tests_properties(PostConnectOperationProviderRegistrarTest.test_getProvidersAfterStartup PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;0;")
add_test(PostConnectOperationProviderRegistrarTest.test_registerProvidersAfterStartup "/home/pi/sdk-folder/sdk-build/core/acsdkPostConnectOperationProviderRegistrar/test/PostConnectOperationProviderRegistrarTest" "--gtest_filter=PostConnectOperationProviderRegistrarTest.test_registerProvidersAfterStartup")
set_tests_properties(PostConnectOperationProviderRegistrarTest.test_registerProvidersAfterStartup PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;3;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/core/acsdkPostConnectOperationProviderRegistrar/test/CMakeLists.txt;0;")
