# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test
# Build directory: /home/pi/sdk-folder/sdk-build/SynchronizeStateSender/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(PostConnectSynchronizeStateSenderTest.test_createWithNullContextManager "/home/pi/sdk-folder/sdk-build/SynchronizeStateSender/test/PostConnectSynchronizeStateSenderTest" "--gtest_filter=PostConnectSynchronizeStateSenderTest.test_createWithNullContextManager")
set_tests_properties(PostConnectSynchronizeStateSenderTest.test_createWithNullContextManager PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;0;")
add_test(PostConnectSynchronizeStateSenderTest.test_createWithMetricRecorder "/home/pi/sdk-folder/sdk-build/SynchronizeStateSender/test/PostConnectSynchronizeStateSenderTest" "--gtest_filter=PostConnectSynchronizeStateSenderTest.test_createWithMetricRecorder")
set_tests_properties(PostConnectSynchronizeStateSenderTest.test_createWithMetricRecorder PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;0;")
add_test(PostConnectSynchronizeStateSenderTest.test_getOperationPriority "/home/pi/sdk-folder/sdk-build/SynchronizeStateSender/test/PostConnectSynchronizeStateSenderTest" "--gtest_filter=PostConnectSynchronizeStateSenderTest.test_getOperationPriority")
set_tests_properties(PostConnectSynchronizeStateSenderTest.test_getOperationPriority PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;0;")
add_test(PostConnectSynchronizeStateSenderTest.test_perfromOperationSendsSynchronizeStateEvent "/home/pi/sdk-folder/sdk-build/SynchronizeStateSender/test/PostConnectSynchronizeStateSenderTest" "--gtest_filter=PostConnectSynchronizeStateSenderTest.test_perfromOperationSendsSynchronizeStateEvent")
set_tests_properties(PostConnectSynchronizeStateSenderTest.test_perfromOperationSendsSynchronizeStateEvent PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;0;")
add_test(PostConnectSynchronizeStateSenderTest.test_performOperationRetriesOnContextFailure "/home/pi/sdk-folder/sdk-build/SynchronizeStateSender/test/PostConnectSynchronizeStateSenderTest" "--gtest_filter=PostConnectSynchronizeStateSenderTest.test_performOperationRetriesOnContextFailure")
set_tests_properties(PostConnectSynchronizeStateSenderTest.test_performOperationRetriesOnContextFailure PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;0;")
add_test(PostConnectSynchronizeStateSenderTest.test_testPerfromOperationRetriesOnUnsuccessfulResponse "/home/pi/sdk-folder/sdk-build/SynchronizeStateSender/test/PostConnectSynchronizeStateSenderTest" "--gtest_filter=PostConnectSynchronizeStateSenderTest.test_testPerfromOperationRetriesOnUnsuccessfulResponse")
set_tests_properties(PostConnectSynchronizeStateSenderTest.test_testPerfromOperationRetriesOnUnsuccessfulResponse PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;0;")
add_test(PostConnectSynchronizeStateSenderTest.test_abortOperationWhenContextRequestInProgress "/home/pi/sdk-folder/sdk-build/SynchronizeStateSender/test/PostConnectSynchronizeStateSenderTest" "--gtest_filter=PostConnectSynchronizeStateSenderTest.test_abortOperationWhenContextRequestInProgress")
set_tests_properties(PostConnectSynchronizeStateSenderTest.test_abortOperationWhenContextRequestInProgress PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;0;")
add_test(PostConnectSynchronizeStateSenderTest.test_abortOperationWhenSendMessageInProgress "/home/pi/sdk-folder/sdk-build/SynchronizeStateSender/test/PostConnectSynchronizeStateSenderTest" "--gtest_filter=PostConnectSynchronizeStateSenderTest.test_abortOperationWhenSendMessageInProgress")
set_tests_properties(PostConnectSynchronizeStateSenderTest.test_abortOperationWhenSendMessageInProgress PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;4;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/SynchronizeStateSender/test/CMakeLists.txt;0;")
