# CMake generated Testfile for 
# Source directory: /home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test
# Build directory: /home/pi/sdk-folder/sdk-build/CapabilityAgents/ApiGateway/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ApiGatewayCapabilityAgentTest.createNoGatewayManager "/home/pi/sdk-folder/sdk-build/CapabilityAgents/ApiGateway/test/ApiGatewayCapabilityAgentTest" "--gtest_filter=ApiGatewayCapabilityAgentTest.createNoGatewayManager")
set_tests_properties(ApiGatewayCapabilityAgentTest.createNoGatewayManager PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;0;")
add_test(ApiGatewayCapabilityAgentTest.createNoAVSGatewayManager "/home/pi/sdk-folder/sdk-build/CapabilityAgents/ApiGateway/test/ApiGatewayCapabilityAgentTest" "--gtest_filter=ApiGatewayCapabilityAgentTest.createNoAVSGatewayManager")
set_tests_properties(ApiGatewayCapabilityAgentTest.createNoAVSGatewayManager PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;0;")
add_test(ApiGatewayCapabilityAgentTest.testNullDirective "/home/pi/sdk-folder/sdk-build/CapabilityAgents/ApiGateway/test/ApiGatewayCapabilityAgentTest" "--gtest_filter=ApiGatewayCapabilityAgentTest.testNullDirective")
set_tests_properties(ApiGatewayCapabilityAgentTest.testNullDirective PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;0;")
add_test(ApiGatewayCapabilityAgentTest.testValidUnknownDirective "/home/pi/sdk-folder/sdk-build/CapabilityAgents/ApiGateway/test/ApiGatewayCapabilityAgentTest" "--gtest_filter=ApiGatewayCapabilityAgentTest.testValidUnknownDirective")
set_tests_properties(ApiGatewayCapabilityAgentTest.testValidUnknownDirective PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;0;")
add_test(ApiGatewayCapabilityAgentTest.testValidDirectiveWithNoPayload "/home/pi/sdk-folder/sdk-build/CapabilityAgents/ApiGateway/test/ApiGatewayCapabilityAgentTest" "--gtest_filter=ApiGatewayCapabilityAgentTest.testValidDirectiveWithNoPayload")
set_tests_properties(ApiGatewayCapabilityAgentTest.testValidDirectiveWithNoPayload PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;0;")
add_test(ApiGatewayCapabilityAgentTest.testValidDirectiveWithInvalidPayload "/home/pi/sdk-folder/sdk-build/CapabilityAgents/ApiGateway/test/ApiGatewayCapabilityAgentTest" "--gtest_filter=ApiGatewayCapabilityAgentTest.testValidDirectiveWithInvalidPayload")
set_tests_properties(ApiGatewayCapabilityAgentTest.testValidDirectiveWithInvalidPayload PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;0;")
add_test(ApiGatewayCapabilityAgentTest.testValidSetGatewayDirective "/home/pi/sdk-folder/sdk-build/CapabilityAgents/ApiGateway/test/ApiGatewayCapabilityAgentTest" "--gtest_filter=ApiGatewayCapabilityAgentTest.testValidSetGatewayDirective")
set_tests_properties(ApiGatewayCapabilityAgentTest.testValidSetGatewayDirective PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;46;GTEST_ADD_TESTS;/home/pi/sdk-folder/sdk-source/avs-device-sdk/tools/Testing.cmake;36;configure_test_command;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;7;discover_unit_tests;/home/pi/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/ApiGateway/test/CMakeLists.txt;0;")
